sudo: false
language: java
jdk:
  - oraclejdk8

before_script:
  - gem install travis

script: mvn clean verify
install: true

after_success:
   - curl -LO https://raw.github.com/igniterealtime/ci-tooling/master/trigger-travis.sh
   - chmod +x trigger-travis.sh
   - ./trigger-travis.sh igniterealtime openfire-bookmarks-plugin $TRAVIS_ACCESS_TOKEN 
