name: Openfire Database Upgrade Tests

env:
  CI: true
  STARTER_VERSION: 21 # The version of the initial DB being installed, as per the ofVersion table

on: push
# ^^ Switching to all, just while testing...
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]



jobs:
  sqlserver:
    name: Test SQL Server Upgrades
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Openfire
      uses: actions/checkout@v2
    - name: Set environment variables
      run: |
        echo "CONNECTION_STRING=jdbc:sqlserver://localhost:1433;databaseName=openfire;applicationName=Openfire" >> $GITHUB_ENV
        echo "CONNECTION_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver" >> $GITHUB_ENV
        echo "CONNECTION_USERNAME=sa" >> $GITHUB_ENV
        echo "CONNECTION_PASSWORD=SecurePa55w0rd" >> $GITHUB_ENV
        OPENFIREVSN=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "OPENFIREVSN=$OPENFIREVSN" >> $GITHUB_ENV
    - name: Download old Openfire database script
      run: curl https://raw.githubusercontent.com/igniterealtime/Openfire/v3.9.3/src/database/openfire_sqlserver.sql > $GITHUB_WORKSPACE/distribution/src/database/openfire_sqlserver.sql
    - name: Start database server and install database
      run: docker-compose -f ./build/ci/compose/mssql.yml up --detach
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build openfire
      run: mvn install
    - name: Build & run update tester
      run: |
        pushd ./build/ci/updater
        mvn package
        java -jar ./target/updaterunner-1.0.0-jar-with-dependencies.jar
